# Generated by Django 3.0.6 on 2020-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('dyastolic', models.IntegerField()),
                ('pulse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(help_text='Введите логин', max_length=20)),
                ('user_name', models.CharField(help_text='Введите имя', max_length=20)),
                ('gender', models.CharField(help_text='Введите пол', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
